// packages/ui-react/src/Button.tsx
import React from 'react';
import { colors } from '@design/ui-core';
import './Button.css';

export interface ButtonProps {
  label?: string;
  primary?: boolean;
  size?: 'small' | 'medium' | 'large';
  onClick?: () => void;
}

export function Button({
  label = 'Button',
  primary = false,
  size = 'medium',
  onClick,
}: ButtonProps) {
  const classes = ['btn', primary ? 'btn-primary' : 'btn-secondary', `btn-${size}`].join(' ');

  return (
    <button
      className={classes}
      onClick={onClick}
      style={
        {
          '--primary-color': colors.primary,
          '--text-color': colors.text,
        } as React.CSSProperties
      }
    >
      {label}
    </button>
  );
}

// packages/ui-svelte/src/Button.svelte
<script lang="ts">
  import { colors } from '@design/ui-core';

  interface Props {
    label?: string;
    primary?: boolean;
    size?: 'small' | 'medium' | 'large';
    onclick?: () => void;
  }

  let { label = 'Button', primary = false, size = 'medium', onclick }: Props = $props();

  const classes = ['btn', primary ? 'btn-primary' : 'btn-secondary', `btn-${size}`].join(' ');
</script>

<button
  class={classes}
  {onclick}
  style="--primary-color: {colors.primary}; --text-color: {colors.text}"
>
  {label}
</button>

<style>
  .btn {
    font-family: system-ui, sans-serif;
    font-weight: 600;
    border: none;
    border-radius: 0.25rem;
    cursor: pointer;
    display: inline-block;
    line-height: 1;
    transition: all 0.2s;
  }

  .btn-primary {
    background-color: var(--primary-color, #0f766e);
    color: white;
  }

  .btn-primary:hover {
    background-color: #0d9488;
  }

  .btn-secondary {
    background-color: var(--text-color, #e5e7eb);
    color: #1f2937;
  }

  .btn-secondary:hover {
    background-color: #d1d5db;
  }

  .btn-small {
    padding: 0.5rem 1rem;
    font-size: 0.875rem;
  }

  .btn-medium {
    padding: 0.75rem 1.5rem;
    font-size: 1rem;
  }

  .btn-large {
    padding: 1rem 2rem;
    font-size: 1.125rem;
  }
</style>
